import sys

sys.path.append("../src/")
import scipy.io
import numpy as np

# toolbox is imported from src
import toolbox as tb
import torch as tch
import re
from vseg.src.vseg import SegmentationMap as VSM

PATTERN = "^(?P<home>.*)\/sub_(?P<subject>\d*)_exp(?P<experiment>\d)_session(?P<session>\d)_cat(?P<cat>\d)_img(?P<img>\d).(?P<ext>.*)"


class Response:

    def __init__(self, file):
        """
        Constructs a Python class from a response .mat file generated by
        psychophysics segmentation task

        Attributes:
        ------------
        self.responseMapping :
        self.Response :
        self.reactionTime :
        self.orderedReactionTime :
        self.timestamps :
        self.totTaskStart_time :
        self.totTaskEnd_time :
        self.taskEndTimes :
        self.taskDur :
        self.orderedResponse :
        self.imName :
        self.testedPairs :
        self.indtestedPairs :

        Parameters:
        -----------
        file : str
        """
        d = self.loadmat_(file)
        self.__dict__ = d["data"]
        self.filename = file
        self.parse_filename()
        self.fields = list(d["data"].keys())
        self.subject = self.filename.split("_")[1]
        self.is_fit = False
        return None

    def parse_filename(self):
        """
        Parses filenames with regex and extracts the following:

        Returns:
        ---------
        self.fileinfo : dict
            keys are "subject", "experiment", "session", "category", "img"

        """
        filename = self.filename
        self.fileinfo = re.match(PATTERN, filename).groupdict()

    def loadmat_(self, filename):
        """Improved loadmat (replacement for scipy.io.loadmat)
        Ensures correct loading of python dictionaries from mat files.

        Inspired by: https://stackoverflow.com/a/29126361/572908
        """

        def _has_struct(elem):
            """Determine if elem is an array
            and if first array item is a struct
            """
            return (
                isinstance(elem, np.ndarray)
                and (elem.size > 0)
                and isinstance(elem[0], scipy.io.matlab.mio5_params.mat_struct)
            )

        def _check_keys(d):
            """checks if entries in dictionary are mat-objects. If yes
            todict is called to change them to nested dictionaries
            """
            for key in d:
                elem = d[key]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[key] = _todict(elem)
                elif _has_struct(elem):
                    d[key] = _tolist(elem)
            return d

        def _todict(matobj):
            """A recursive function which constructs from
            matobjects nested dictionaries
            """
            d = {}
            for strg in matobj._fieldnames:
                elem = matobj.__dict__[strg]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[strg] = _todict(elem)
                elif _has_struct(elem):
                    d[strg] = _tolist(elem)
                else:
                    d[strg] = elem
            return d

        def _tolist(ndarray):
            """A recursive function which constructs lists from cellarrays
            (which are loaded as numpy ndarrays), recursing into the
            elements if they contain matobjects.
            """
            elem_list = []
            for sub_elem in ndarray:
                if isinstance(sub_elem, scipy.io.matlab.mio5_params.mat_struct):
                    elem_list.append(_todict(sub_elem))
                elif _has_struct(sub_elem):
                    elem_list.append(_tolist(sub_elem))
                else:
                    elem_list.append(sub_elem)
            return elem_list

        data = scipy.io.loadmat(filename, struct_as_record=False, squeeze_me=True)
        return _check_keys(data)

    def get_tested_pairs(self, transform=True, return_rt=True, all_pairs=False):
        """
        Gets the list of tested pairs and their coordinates

        Parameters:
        ------------
        transform : bool
            if True, then transforms the coordinate system to numpy-based
            coordinates
        return_rt : bool, deprecated
            if True, return self.reactionTime for pair in self.testedPairs
        all_pairs : bool
            if True, use all possible combinations of pairs from
                self.testedPairs
            if False, use only pairs that were actually tested
                and have a reaction time
        """
        tested_pairs = self.testedPairs
        if all_pairs:
            uniques = np.unique(tested_pairs)
            tested_pairs = []
            for i in range(len(uniques)):
                for j in range(i + 1, len(uniques)):
                    tested_pairs.append([uniques[i], uniques[j]])
        _pair_coords = [
            (
                [self.xGrid[pair[0] - 1], self.yGrid[pair[0] - 1]],
                [self.xGrid[pair[1] - 1], self.yGrid[pair[1] - 1]],
            )
            for pair in tested_pairs
        ]

        if transform:
            transform = lambda x: [
                tb.transform_coord_system(x[0]),
                tb.transform_coord_system(x[1]),
            ]

            pair_coords = [transform(coord) for coord in _pair_coords]
        else:
            pair_coords = _pair_coords

        if return_rt:
            # deprecated
            assert len(self.testedPairs) == len(self.reactionTime)
            out = (pair_coords, self.reactionTime)

        return pair_coords

    def get_fit_data(self):
        """
        Extracts the data that is necessary to fit Vseg
        """
        resp = self.Response
        tresp = tch.tensor(np.array(resp, float))

        indtestedPairs = self.indtestedPairs
        tindtestedPairs = tch.tensor(np.array(indtestedPairs, float))
        tindtestedPairs = tindtestedPairs.reshape(resp.shape[0])
        tindtestedPairs = tindtestedPairs.long()

        xGrid = self.xGrid
        yGrid = self.yGrid

        nGrid = int((xGrid.shape[0]) ** (0.5))
        n_seg = self.kSeg
        self.tresp = tresp
        self.tindtestedPairs = tindtestedPairs
        self.n_grid = nGrid
        self.n_seg = n_seg

    def _fit(
        self,
        lap_reg=5,
        lr=1e-1,
        sav_iter=True,
        max_iter=10000,
        tol=1e-6,
    ):
        self.get_fit_data()
        tch.manual_seed(10)
        seg_map = VSM(self.kSeg, self.n_grid, device="cpu")
        inferred_proba_maps = seg_map.fit(
            self.tresp,
            self.tindtestedPairs - 1,
            lap_reg=lap_reg,
            lr=lr,
            max_iter=max_iter,
            tol=tol,
            save_iter=sav_iter,
        )
        seg_proba_maps = (
            inferred_proba_maps.reshape(self.n_seg, self.n_grid, self.n_grid)
            .cpu()
            .detach()
            .numpy()
        )
        loss = np.zeros(len(seg_map.loss_iter))
        for i in range(len(seg_map.loss_iter)):
            loss[i] = seg_map.loss_iter[i].detach().numpy()

        return seg_map, inferred_proba_maps, seg_proba_maps, loss

    def fit(self):
        self.seg_map, self.inferred_proba_maps, self.seg_proba_maps, self.loss = (
            self._fit()
        )

        self.is_fit = True
