import sys

sys.path.append("../src/")
import scipy.io
import numpy as np
import toolbox as tb
from scipy.spatial.distance import jensenshannon
from scipy.optimize import basinhopping
from scipy.optimize import dual_annealing
from scipy.stats import iqr
from collections import Counter
from SegmentationMap import SegmentationMap as SM
from copy import deepcopy

# toolbox is imported from src
import os
import toolbox as tb
import dynamics
import torch as tch
import pandas as pd
from scipy.io import loadmat
import re
from glob import glob as glob
from natsort import natsorted as ns
from vseg.src.vseg import SegmentationMap as VSM
from numpy.lib.stride_tricks import sliding_window_view

PATTERN = "^(?P<home>.*)\/sub_(?P<subject>\d*)_exp(?P<experiment>\d)_session(?P<session>\d)_cat(?P<cat>\d)_img(?P<img>\d).(?P<ext>.*)"
FITS_DIR = "/Users/tb/Documents/lab/projects/em_iteration_analysis"


class Response:

    def __init__(self, homedir, file):
        """
        Constructs a Python class from a response .mat file generated by
        psychophysics segmentation task

        Attributes:
        ------------
        self.responseMapping :
        self.Response :
        self.reactionTime :
        self.orderedReactionTime :
        self.timestamps :
        self.totTaskStart_time :
        self.totTaskEnd_time :
        self.taskEndTimes :
        self.taskDur :
        self.orderedResponse :
        self.imName :
        self.testedPairs :
        self.indtestedPairs :

        Parameters:
        -----------
        homedir : str
        file : str
        """
        d = self.loadmat_(file)
        self.__dict__ = d["data"]
        self.filename = file
        self.homedir = homedir
        self.parse_filename()
        self.fields = list(d["data"].keys())
        self.subject = self.filename.split("_")[1]
        self.is_fit = False
        return None

    def parse_filename(self):
        """
        Parses filename with regex and extracts the following:
        - subject
        - experiment
        - session
        - image category
        - image id

        Returns:
        ---------
        self.fileinfo : dict
            keys are "subject", "experiment", "session", "category", "img"

        """
        filename = os.path.join(self.homedir, self.filename)
        self.fileinfo = re.match(PATTERN, filename).groupdict()

    def loadmat_(self, filename):
        """Improved loadmat (replacement for scipy.io.loadmat)
        Ensures correct loading of python dictionaries from mat files.

        Inspired by: https://stackoverflow.com/a/29126361/572908
        """

        def _has_struct(elem):
            """Determine if elem is an array
            and if first array item is a struct
            """
            return (
                isinstance(elem, np.ndarray)
                and (elem.size > 0)
                and isinstance(elem[0], scipy.io.matlab.mio5_params.mat_struct)
            )

        def _check_keys(d):
            """checks if entries in dictionary are mat-objects. If yes
            todict is called to change them to nested dictionaries
            """
            for key in d:
                elem = d[key]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[key] = _todict(elem)
                elif _has_struct(elem):
                    d[key] = _tolist(elem)
            return d

        def _todict(matobj):
            """A recursive function which constructs from
            matobjects nested dictionaries
            """
            d = {}
            for strg in matobj._fieldnames:
                elem = matobj.__dict__[strg]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[strg] = _todict(elem)
                elif _has_struct(elem):
                    d[strg] = _tolist(elem)
                else:
                    d[strg] = elem
            return d

        def _tolist(ndarray):
            """A recursive function which constructs lists from cellarrays
            (which are loaded as numpy ndarrays), recursing into the
            elements if they contain matobjects.
            """
            elem_list = []
            for sub_elem in ndarray:
                if isinstance(sub_elem, scipy.io.matlab.mio5_params.mat_struct):
                    elem_list.append(_todict(sub_elem))
                elif _has_struct(sub_elem):
                    elem_list.append(_tolist(sub_elem))
                else:
                    elem_list.append(sub_elem)
            return elem_list

        data = scipy.io.loadmat(filename, struct_as_record=False, squeeze_me=True)
        return _check_keys(data)

    def get_np_coords(self, transform=True):
        """
        Transform x,y coordinates defined in file to numpy array coords
        """
        _points = np.concatenate(
            [self.xGrid[..., np.newaxis], self.yGrid[..., np.newaxis]], axis=1
        )
        if transform:
            points = [tb.transform_coord_system(coord) for coord in _points]

        self.points = points

    def get_tested_pairs(self, transform=True, return_rt=True, all_pairs=False):
        """
        Gets the list of tested pairs and their numpy coordinates

        Parameters:
        ------------
        transform : bool
            if True, then transforms the coordinate system to numpy-based
            coordinates
        return_rt : bool, deprecated
            if True, return self.reactionTime for pair in self.testedPairs
        all_pairs : bool
            if True, use all possible combinations of pairs from
                self.testedPairs
            if False, use only pairs that were actually tested
                and have a reaction time
        """
        tested_pairs = self.testedPairs
        if all_pairs:
            uniques = np.unique(tested_pairs)
            tested_pairs = []
            for i in range(len(uniques)):
                for j in range(i + 1, len(uniques)):
                    tested_pairs.append([uniques[i], uniques[j]])
        _pair_coords = [
            (
                [self.xGrid[pair[0] - 1], self.yGrid[pair[0] - 1]],
                [self.xGrid[pair[1] - 1], self.yGrid[pair[1] - 1]],
            )
            for pair in tested_pairs
        ]

        if transform:
            transform = lambda x: [
                tb.transform_coord_system(x[0]),
                tb.transform_coord_system(x[1]),
            ]

            pair_coords = [transform(coord) for coord in _pair_coords]
        else:
            pair_coords = _pair_coords

        if return_rt:
            # deprecated
            assert len(self.testedPairs) == len(self.reactionTime)
            out = (pair_coords, self.reactionTime)

        return pair_coords

    def get_fit_data(self):
        """
        Extracts the data that is necessary to fit Vseg,
        """
        resp = self.Response
        tresp = tch.tensor(np.array(resp, float))

        indtestedPairs = self.indtestedPairs
        tindtestedPairs = tch.tensor(np.array(indtestedPairs, float))
        tindtestedPairs = tindtestedPairs.reshape(resp.shape[0])
        tindtestedPairs = tindtestedPairs.long()

        xGrid = self.xGrid
        yGrid = self.yGrid

        nGrid = int((xGrid.shape[0]) ** (0.5))
        n_seg = self.kSeg
        self.tresp = tresp
        self.tindtestedPairs = tindtestedPairs
        self.n_grid = nGrid
        self.n_seg = n_seg

    def _fit(
        self,
        lap_reg=5,
        lr=1e-1,
        sav_iter=True,
        max_iter=10000,
        tol=1e-6,
    ):
        """
        Runs vseg using PyTorch, but doesn't work :(

        """
        self.get_fit_data()
        tch.manual_seed(10)
        seg_map = VSM(self.kSeg, self.n_grid, device="cpu")
        inferred_proba_maps = seg_map.fit(
            self.tresp,
            self.tindtestedPairs - 1,
            lap_reg=lap_reg,
            lr=lr,
            max_iter=max_iter,
            tol=tol,
            save_iter=sav_iter,
        )
        seg_proba_maps = (
            inferred_proba_maps.reshape(self.n_seg, self.n_grid, self.n_grid)
            .cpu()
            .detach()
            .numpy()
        )
        loss = np.zeros(len(seg_map.loss_iter))
        for i in range(len(seg_map.loss_iter)):
            loss[i] = seg_map.loss_iter[i].detach().numpy()

        return seg_map, inferred_proba_maps, seg_proba_maps, loss

    def fit(self, preloaded=True):
        """
        Get preloaded maps that are fit by vseg, using filename information

        Parameters:
        -----------
        preloaded : bool
            default is True, does not work for False yet
        """
        os.chdir(self.homedir)
        print(self.homedir)
        if not preloaded:
            self.seg_map, self.inferred_proba_maps, self.seg_proba_maps, self.loss = (
                self._fit()
            )

        else:
            home = "data/fits/"
            filename = "fits_sub_{}_exp{}_session{}_cat{}_img{}.mat".format(
                self.fileinfo["subject"],
                self.fileinfo["experiment"],
                self.fileinfo["session"],
                self.fileinfo["cat"],
                self.fileinfo["img"],
            )

            self.fit_file = home + filename

            self.fit_pmap = np.moveaxis(loadmat(self.fit_file)["seg_map"], -1, 1)

            self.fit_segmap = self.fit_pmap.argmax(0)
            self.large_fit_segmap = tb.scale_im_up(self.fit_segmap, self.image.shape[0])

            self.human_seg_flag = np.asarray(
                [self._get_fit_seg_flag(pair) for pair in self.testedPairs]
            )

            self.human_psame = np.asarray(
                [self._get_fit_psame(pair) for pair in self.testedPairs]
            )

            self.is_fit = True

    def _get_fit_seg_flag(self, grid_idxs):
        """
        Returns the response according the participants' final segmentation map

        Parameters:
        ------------
        grid_idxs : list
            the index of the point in the trial grid

        """
        unravel_idx = lambda x: np.asarray(
            np.unravel_index(x - 1, self.fit_segmap.shape[:2])
        ).T

        idx_a = unravel_idx(grid_idxs[0])
        idx_b = unravel_idx(grid_idxs[1])
        seg_flag_a = self.fit_segmap[idx_a[0], idx_a[1]]
        seg_flag_b = self.fit_segmap[idx_b[0], idx_b[1]]

        return seg_flag_a == seg_flag_b

    def _get_fit_psame(self, grid_idxs):
        """
        Returns the segment probabilities decoded from participant responses
        """
        unravel_idx = lambda x: np.asarray(
            np.unravel_index(x - 1, self.fit_segmap.shape[:2])
        ).T

        vec_a = self.fit_pmap[
            :, unravel_idx(grid_idxs[0])[0], unravel_idx(grid_idxs[0])[1]
        ]
        vec_b = self.fit_pmap[
            :, unravel_idx(grid_idxs[1])[0], unravel_idx(grid_idxs[1])[1]
        ]

        psame = np.dot(vec_a, vec_b)

        return psame

    def sample_pmap(self, resize=True):
        """
        Draw a sample from the probabilistic segmentation map decoded from participant responses
        """
        assert hasattr(self, "fit_pmap")
        _sample_pmap = lambda x: np.random.choice(list(range(len(x))), size=1, p=x)

        stop = -1
        # Sample so that every segment is assigned to atleast one pixel
        while stop < 0:
            present = 0
            sample = np.apply_along_axis(_sample_pmap, 0, self.fit_pmap).squeeze()
            for value in range(self.kSeg):
                if value in sample:
                    present += 1
            if present < self.kSeg:
                stop = -1
            else:
                stop = 0

        if resize:
            sample = tb.scale_im_up(sample, self.image.shape[0])
        return sample

    # DEPRECATED
    if False:

        def loss_function(
            self,
            value,
            loss_param="automult",
            loss_type="jsd",
            penalize_zeros=True,
            conv_failure="argmax",
            mode="base",
            use_boundary=None,
            return_data=False,
            split_by_response=True,
        ):
            if (loss_param == "automult") and (use_boundary is not None):
                model_data_full = self._sweep(
                    value,
                    col=loss_param,
                    conv_failure=conv_failure,
                    mode=mode,
                    use_boundary=use_boundary,
                )
            else:
                model_data_full = self._sweep(
                    value, col=loss_param, conv_failure=conv_failure, mode=mode
                )
            n_zeros = len(self.reactiontime) - np.count_nonzero(model_data_full)
            if loss_type == "mle":
                n_zeros *= 1000
            human_data_full = self.reactiontime

            model_data = model_data_full[model_data_full != 0]
            human_data = human_data_full[model_data_full != 0]

            m_log_data = np.log(model_data)
            h_log_data = np.log(human_data)

            model_resc = (m_log_data - np.min(m_log_data)) / np.ptp(m_log_data)
            human_resc = (h_log_data - np.min(h_log_data)) / np.ptp(h_log_data)
            if return_data and not split_by_response:
                return model_resc, human_resc

            if split_by_response:
                human_responses = self.response.astype("bool")[model_data_full != 0]

                if return_data:
                    return model_resc, human_resc, human_responses

                model_split = {
                    true: model_resc[human_responses],
                    false: model_resc[~human_responses],
                }

                human_split = {
                    true: human_resc[human_responses],
                    false: human_resc[~human_responses],
                }

                if loss_type == "jsd":
                    terms = []
                    for i in [true, false]:
                        terms.append(jensenshannon(human_split[i], model_split[i]))
                elif loss_type == "mse":
                    terms = []
                    for i in [true, false]:
                        terms.append(
                            (np.mean(human_split[i]) - np.mean(model_split[i])) ** 2
                        )
                elif loss_type == "mle":
                    lkls_split = {
                        true: tb.emp_lkl_mkii(model_split[true], human_split[true]),
                        false: tb.emp_lkl_mkii(model_split[false], human_split[false]),
                    }

                    lkls = np.zeros(human_data.shape)
                    lkls[human_responses] = lkls_split[true]
                    lkls[~human_responses] = lkls_split[false]
                    self.lkls = lkls

                    terms = []
                    for i in [true, false]:
                        terms.append(lkls_split[i])

                elif loss_type == "gaussian_mle":
                    lkls_split = {
                        true: tb.gaussian_lkl(model_split[true], human_split[true]),
                        false: tb.gaussian_lkl(model_split[false], human_split[false]),
                    }

                    lkls = np.zeros(human_data.shape)
                    lkls[human_responses] = lkls_split[true]
                    lkls[~human_responses] = lkls_split[false]
                    self.lkls = lkls

                    terms = []
                    for i in [true, false]:
                        terms.append(lkls_split[i])

                term1 = sum(terms)

            else:
                if loss_type == "jsd":
                    term1 = jensenshannon(human_resc, model_resc)
                elif loss_type == "mse":
                    term1 = (np.mean(human_resc) - np.mean(model_resc)) ** 2
                elif loss_type == "mle":
                    lkls = tb.emp_lkl_mkii(human_resc, model_resc)
                    term1 = lkls

            if penalize_zeros:
                loss = term1 + n_zeros
            else:
                loss = term1

            return loss

        def optimize_params_2d(
            self,
            init_guess=none,
            verbose=true,
            loss_type="mle",
            split_by_response=true,
            penalize_zeros=true,
            annealing_step=true,
        ):
            assert self.is_fit

            if init_guess is not none:
                init_guess = init_guess
            else:
                init_guess = np.array([0.01, 5])

            hyperparams = {
                "x0": init_guess,
                "stepsize": 0.1,
                "t": 1,
                "niter_success": 100,
            }

            loss = lambda x: self.loss_function(
                x[0],
                loss_param="automult",
                loss_type=loss_type,
                penalize_zeros=penalize_zeros,
                mode="all",
                split_by_response=split_by_response,
                use_boundary=x[1],
            )

            opt_res = basinhopping(
                loss,
                **hyperparams,
                minimizer_kwargs={"bounds": [(1e-4, 1), (1e-4, 10)]},
                disp=verbose
            )

            if annealing_step:
                optt_res = dual_annealing(
                    loss,
                    [
                        (
                            opt_res.x[0] - 0.5 * opt_res.x[0],
                            opt_res.x[0] + 0.5 * opt_res.x[0],
                        ),
                        (
                            opt_res.x[1] - 0.5 * opt_res.x[1],
                            opt_res.x[1] + 0.5 * opt_res.x[1],
                        ),
                    ],
                    x0=opt_res.x,
                    callback=print,
                    maxiter=100,
                )

                res = optt_res
            else:
                res = opt_res

            self.opt_automult_param2d = res.x
            self.opt_automult_error2d = res.fun

        def optimize_params(
            self,
            params=["automult", "online_rt", "ei_rt", "wei_rt"],
            verbose=false,
            loss_type="jsd",
            split_by_response=true,
            penalize_zeros=true,
            annealing_step=true,
            mode="base",
            add_auto_bound=none,
        ):
            """
            parameters:
            ------------
            optimizes model parameters to match distribution of human data.
            hyperparameters are not function arguments, but can be changed below

            params : list of str
                "automult" : derivative parameter for flexmm model "online_bound":
                bound parameter for flexmm model "ei_bound": bound parameter for
                vanilla ei model "wei_bound" : bound parameter for weighted ei model

            loss_type : str
                "jsd" : uses jensen-shannon divergence
                "mle" : uses empirical likelihood function
                    from model data cdf
                "mse" : uses the mean-square error
                "gaussian_mle" : uses a likelihood function that assumes the
                    model distribution is gaussian
            """
            assert self.is_fit

            if mode == "base":
                assert hasattr(
                    self, "basemodel"
                ), "must run basemodel before optimizing params"

            self.opt_params = {}
            self.opt_error = {}

            auto_mult_init = np.array([0.01])

            hyperparams = {
                "automult": {
                    "x0": auto_mult_init,
                    "stepsize": 0.005,
                    "t": 0.01,
                    "niter_success": 100,
                },
                "online_rt": {"x0": 5, "stepsize": 0.1, "t": 1, "niter_success": 100},
                "ei_rt": {"x0": 5, "stepsize": 0.1, "t": 1, "niter_success": 100},
                "wei_rt": {"x0": 2, "stepsize": 1, "t": 0.001, "niter_success": 100},
            }

            if loss_type == "mle":
                hyperparams = {
                    "automult": {
                        "x0": auto_mult_init,
                        "stepsize": 0.005,
                        "t": 100,
                        "niter_success": 100,
                    },
                    "online_rt": {
                        "x0": 5,
                        "stepsize": 0.1,
                        "t": 100,
                        "niter_success": 100,
                    },
                    "ei_rt": {"x0": 5, "stepsize": 0.1, "t": 100, "niter_success": 100},
                    "wei_rt": {
                        "x0": 2,
                        "stepsize": 1,
                        "t": 0.001,
                        "niter_success": 100,
                    },
                }

            if loss_type == "mse":
                hyperparams.update(
                    {
                        "wei_rt": {
                            "x0": 2,
                            "stepsize": 1,
                            "t": 0.001,
                            "niter_success": 20,
                        }
                    }
                )

            for param in params:
                if verbose:
                    print(
                        "\n running basinhopping optimization for parameter: {} \n".format(
                            param
                        )
                    )
                if add_auto_bound is not none:
                    loss = lambda x: self.loss_function(
                        x,
                        loss_param=param,
                        loss_type=loss_type,
                        penalize_zeros=penalize_zeros,
                        mode=mode,
                        split_by_response=split_by_response,
                        use_boundary=add_auto_bound,
                    )
                else:
                    loss = lambda x: self.loss_function(
                        x,
                        loss_param=param,
                        loss_type=loss_type,
                        penalize_zeros=penalize_zeros,
                        mode=mode,
                        split_by_response=split_by_response,
                    )
                cbf = lambda x, f, accept: true if (f < (1e-3)) and (accept) else false
                opt_res = basinhopping(
                    loss,
                    **hyperparams[param],
                    minimizer_kwargs={"bounds": [(1e-4, 10)]},
                    disp=verbose,
                    callback=cbf
                )
                if verbose:
                    print("\n \t running annealing step ... ")
                if annealing_step:
                    if param != "automult":
                        optt_res = dual_annealing(
                            loss,
                            [
                                (
                                    opt_res.x[0] - 0.5 * opt_res.x[0],
                                    opt_res.x[0] + 0.5 * opt_res.x[0],
                                )
                            ],
                            x0=opt_res.x,
                            callback=print,
                            maxiter=100,
                        )
                    else:
                        optt_res = dual_annealing(
                            loss,
                            [
                                (
                                    opt_res.x[0] - 0.1 * opt_res.x[0],
                                    opt_res.x[0] + 0.1 * opt_res.x[0],
                                )
                            ],
                            x0=opt_res.x,
                            callback=print,
                            maxiter=20,
                        )
                    res = optt_res
                else:
                    res = opt_res

                self.opt_error[param] = res.fun
                self.opt_params[param] = res.x[0]

        def _sweep(
            self,
            value,
            col="automult",
            conv_failure="argmax",
            mode="base",
            use_boundary=none,
        ):
            """
            parameters:
            -----------
            value : float
            col : str
                "automult" : derivative parameter for flexmm model
                "online_bound": bound parameter for flexmm model
                "ei_bound": bound parameter for vanilla ei model
                "wei_bound" : bound parameter for weighted ei model

            returns:
            ---------
            rts : array of reaction times
            """
            if mode == "base":
                assert hasattr(self, "basemodel")

                if col == "automult":
                    if use_boundary is not none:
                        rts = self.basemodel._get_rt_from_deriv(
                            value,
                            return_mean=true,
                            failure_mode=conv_failure,
                            use_boundary=use_boundary,
                        )
                    else:
                        rts = self.basemodel._get_rt_from_deriv(
                            value, return_mean=true, failure_mode=conv_failure
                        )
                if col == "online_rt":
                    rts = self.basemodel._get_rt_from_boundary(
                        value, param="logits", return_mean=true
                    )
                elif col == "ei_rt":
                    rts = self.basemodel._get_rt_from_boundary(
                        value, param="ei_logits", return_mean=true
                    )
                elif col == "wei_rt":
                    rts = self.basemodel._get_rt_from_boundary(
                        value, param="wei_logits", return_mean=true
                    )
            else:
                if col == "automult":
                    if use_boundary is not none:
                        rts = dynamics._get_rt_from_deriv(
                            self.smooth_logits,
                            self.logit_deriv,
                            value,
                            return_mean=true,
                            failure_mode=conv_failure,
                            mean_axis=(0, -1),
                            use_boundary=use_boundary,
                        )
                    else:
                        rts = dynamics._get_rt_from_deriv(
                            self.smooth_logits,
                            self.logit_deriv,
                            value,
                            return_mean=true,
                            failure_mode=conv_failure,
                            mean_axis=(0, -1),
                        )
                if col == "online_rt":
                    rts = dynamics._get_rt_from_boundary(
                        self.logits,
                        value,
                        return_mean=true,
                        output_flat=false,
                        mean_axis=(0, -1),
                    )
                elif col == "ei_rt":
                    rts = dynamics._get_rt_from_boundary(
                        self.ei_logits,
                        value,
                        return_mean=true,
                        output_flat=false,
                        mean_axis=(0, -1),
                    )
                elif col == "wei_rt":
                    rts = dynamics._get_rt_from_boundary(
                        self.wei_logits,
                        value,
                        return_mean=true,
                        output_flat=false,
                        mean_axis=(0, -1),
                    )

            return rts

    def run_dynamics_model(
        self,
        n_trials=2,
        smooth=1,
        noisy_init=True,
        n_pseudocoords=4,
        layer=1,
        random_init=False,
        n_pca=6,
    ):
        """
        Parameters:
        ------------
        n_trials : int
            number of trials that the model is run, different trials because
            of different pseudocoords and (potentially) different initializations
        smooth : int
            1 if applying spatial smoothing, 0 if ablating
        noisy_init : bool
            True if sampling from participant pmap for intial guess, else use MAP
            segment classes
        n_pseudocoords : int
            The number of pseudocoords around each grid, the number of points being
            averaged is n^2 given n pseudocoords
        layer = int
            The layer to use in FlexMM
        random_init = False
            False if standard initialization, True if ablating
        n_pca = int
            Default is 6

        """
        self.fit()

        self.Models = []

        n_iter = []

        for i in range(n_trials):
            print("Fitting segmap trial {}".format(i))
            Model = SM((i + 1, self.image), mode="array")

            if noisy_init:
                human_prior = self.sample_pmap()
                init_eps = 0.05
            else:
                human_prior = self.large_fit_segmap
                init_eps = 0.01

            if random_init:
                human_prior = np.random.choice(
                    range(self.kSeg), size=(self.image.shape[0], self.image.shape[1])
                )

                init_eps = 0.5 * (1 / (self.kSeg - 1)) - 1e-4

            Model.fit_model(
                model="c",
                n_components=np.array([self.kSeg]),
                layer_stop=layer,
                keep=True,
                init=human_prior,
                init_eps=init_eps,
                spatial_smoothing=smooth,
                n_pca=n_pca,
            )

            Model.parse_layer(layer)

            self.get_np_coords()
            points = self.points
            pairs = self.get_tested_pairs(all_pairs=False)

            Model.get_iter_info(
                points, pairs, self.testedPairs, n_pseudocoords=n_pseudocoords
            )

            n_iter.append(Model.n_iter)

            self.Models.append(Model)

            # check logits for infs
            for attr in ["logits"]:
                struct = Model.__dict__[attr]
                assert (
                    struct[(struct == np.inf) | (struct == -np.inf)].size == 0
                ), "inf values present"

        for Model in self.Models:
            if Model.logits.shape[-1] < max(n_iter):
                pad_length = max(n_iter) - Model.logits.shape[-1]

                Model.sfs_t = np.pad(
                    Model.sfs_t, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )
                Model.logits = np.pad(
                    Model.logits, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )

        self.seg_flags = np.asarray([Model.sfs_t for Model in self.Models])
        self.logits = np.asarray([Model.logits for Model in self.Models])

    def run_multilayer_model(
        self, n_layers=5, smooth=1, noisy_init=True, n_pseudocoords=4
    ):
        """
        Not used but allows for the possibility of model fitting across
        multiple layers
        """
        self.fit()

        self.Models = []

        Model = SM((1, self.image), mode="array")
        n_iter = []

        if noisy_init:
            human_prior = self.sample_pmap()
        else:
            human_prior = self.large_fit_segmap

        Model.fit_model(
            model="c",
            n_components=np.array([self.kSeg]),
            layer_stop=n_layers,
            keep=True,
            init=human_prior,
            init_eps=0.05,
            spatial_smoothing=smooth,
        )

        for i in range(1, n_layers + 1):
            Layer = deepcopy(Model)
            Layer.parse_layer(i)

            self.get_np_coords()
            points = self.points
            pairs = self.get_tested_pairs(all_pairs=False)

            Layer.get_iter_info(
                points, pairs, self.testedPairs, n_pseudocoords=n_pseudocoords
            )

            n_iter.append(Layer.n_iter)

            Layer.get_ei_info(pairs, weighted=True)

            self.Models.append(Layer)

        for Model in self.Models:
            if Model.logits.shape[-1] < max(n_iter):
                pad_length = max(n_iter) - Model.logits.shape[-1]

                Model.sfs_t = np.pad(
                    Model.sfs_t, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )
                Model.logits = np.pad(
                    Model.logits, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )
                Model.ei_logits = np.pad(
                    Model.ei_logits, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )
                Model.wei_logits = np.pad(
                    Model.wei_logits, [(0, 0), (0, 0), (0, pad_length)], mode="edge"
                )
        self.seg_flags = np.asarray([Model.sfs_t for Model in self.Models])
        self.logits = np.asarray([Model.logits for Model in self.Models])
        # self.logits = np.asarray([self.Models[-1].logits] * n_layers)
        self.ei_logits = np.asarray([self.Models[-1].ei_logits] * n_layers)
        self.wei_logits = np.asarray([self.Models[-1].wei_logits] * n_layers)

        self.smooth_logits = sliding_window_view(self.logits, 3, axis=-1).mean(-1)

        diff = lambda x: (x[-1] - x[0]) / len(x)
        self.logit_deriv = np.apply_along_axis(
            diff, -1, sliding_window_view(self.logits, 3, axis=-1)
        )

    def set_layer_in_multilayer(self, layer, n_pseudocoords=20):
        Model = self.Models[0]
        Model.parse_layer(layer)

        self.get_np_coords()
        points = self.points
        pairs = self.get_tested_pairs(all_pairs=False)

        Model.get_iter_info(
            points, pairs, self.testedPairs, n_pseudocoords=n_pseudocoords
        )

        conv_logits = Model.logits[..., -1].reshape(-1)

        ei_noise = iqr(conv_logits, rng=(25, 75))
        wei_noise = iqr(conv_logits, rng=(10, 90))

        Model.get_ei_info(
            pairs, weighted=True, noise=ei_noise, weighted_noise=wei_noise
        )

        # check logits for infs
        for attr in ["logits"]:
            struct = Model.__dict__[attr]
            assert (
                struct[(struct == np.inf) | (struct == -np.inf)].size == 0
            ), "inf values present"

        self.seg_flags = Model.sfs_t
        self.logits = Model.logits
        self.ei_logits = Model.ei_logits
        self.wei_logits = Model.wei_logits

        self.smooth_logits = sliding_window_view(self.logits, 3, axis=-1).mean(-1)

        diff = lambda x: (x[-1] - x[0]) / len(x)
        self.logit_deriv = np.apply_along_axis(
            diff, -1, sliding_window_view(self.logits, 3, axis=-1)
        )
