import sys

sys.path.append("../src/")
import scipy.io
import numpy as np
import toolbox as tb
from scipy.spatial.distance import jensenshannon
from collections import Counter
from SegmentationMap import SegmentationMap as SM

# toolbox is imported from src
import toolbox as tb
import torch as tch
import pandas as pd
from scipy.io import loadmat
import re
from glob import glob as glob
from natsort import natsorted as ns
from vseg.src.vseg import SegmentationMap as VSM

PATTERN = "^(?P<home>.*)\/sub_(?P<subject>\d*)_exp(?P<experiment>\d)_session(?P<session>\d)_cat(?P<cat>\d)_img(?P<img>\d).(?P<ext>.*)"


class Response:

    def __init__(self, file):
        """
        Constructs a Python class from a response .mat file generated by
        psychophysics segmentation task

        Attributes:
        ------------
        self.responseMapping :
        self.Response :
        self.reactionTime :
        self.orderedReactionTime :
        self.timestamps :
        self.totTaskStart_time :
        self.totTaskEnd_time :
        self.taskEndTimes :
        self.taskDur :
        self.orderedResponse :
        self.imName :
        self.testedPairs :
        self.indtestedPairs :

        Parameters:
        -----------
        file : str
        """
        d = self.loadmat_(file)
        self.__dict__ = d["data"]
        self.filename = file
        self.parse_filename()
        self.fields = list(d["data"].keys())
        self.subject = self.filename.split("_")[1]
        self.is_fit = False
        return None

    def parse_filename(self):
        """
        Parses filenames with regex and extracts the following:

        Returns:
        ---------
        self.fileinfo : dict
            keys are "subject", "experiment", "session", "category", "img"

        """
        filename = self.filename
        self.fileinfo = re.match(PATTERN, filename).groupdict()

    def loadmat_(self, filename):
        """Improved loadmat (replacement for scipy.io.loadmat)
        Ensures correct loading of python dictionaries from mat files.

        Inspired by: https://stackoverflow.com/a/29126361/572908
        """

        def _has_struct(elem):
            """Determine if elem is an array
            and if first array item is a struct
            """
            return (
                isinstance(elem, np.ndarray)
                and (elem.size > 0)
                and isinstance(elem[0], scipy.io.matlab.mio5_params.mat_struct)
            )

        def _check_keys(d):
            """checks if entries in dictionary are mat-objects. If yes
            todict is called to change them to nested dictionaries
            """
            for key in d:
                elem = d[key]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[key] = _todict(elem)
                elif _has_struct(elem):
                    d[key] = _tolist(elem)
            return d

        def _todict(matobj):
            """A recursive function which constructs from
            matobjects nested dictionaries
            """
            d = {}
            for strg in matobj._fieldnames:
                elem = matobj.__dict__[strg]
                if isinstance(elem, scipy.io.matlab.mio5_params.mat_struct):
                    d[strg] = _todict(elem)
                elif _has_struct(elem):
                    d[strg] = _tolist(elem)
                else:
                    d[strg] = elem
            return d

        def _tolist(ndarray):
            """A recursive function which constructs lists from cellarrays
            (which are loaded as numpy ndarrays), recursing into the
            elements if they contain matobjects.
            """
            elem_list = []
            for sub_elem in ndarray:
                if isinstance(sub_elem, scipy.io.matlab.mio5_params.mat_struct):
                    elem_list.append(_todict(sub_elem))
                elif _has_struct(sub_elem):
                    elem_list.append(_tolist(sub_elem))
                else:
                    elem_list.append(sub_elem)
            return elem_list

        data = scipy.io.loadmat(filename, struct_as_record=False, squeeze_me=True)
        return _check_keys(data)

    def get_np_coords(self, transform=True):
        _points = np.concatenate(
            [self.xGrid[..., np.newaxis], self.yGrid[..., np.newaxis]], axis=1
        )
        if transform:
            points = [tb.transform_coord_system(coord) for coord in _points]

        self.points = points

    def get_tested_pairs(self, transform=True, return_rt=True, all_pairs=False):
        """
        Gets the list of tested pairs and their numpy coordinates

        Parameters:
        ------------
        transform : bool
            if True, then transforms the coordinate system to numpy-based
            coordinates
        return_rt : bool, deprecated
            if True, return self.reactionTime for pair in self.testedPairs
        all_pairs : bool
            if True, use all possible combinations of pairs from
                self.testedPairs
            if False, use only pairs that were actually tested
                and have a reaction time
        """
        tested_pairs = self.testedPairs
        if all_pairs:
            uniques = np.unique(tested_pairs)
            tested_pairs = []
            for i in range(len(uniques)):
                for j in range(i + 1, len(uniques)):
                    tested_pairs.append([uniques[i], uniques[j]])
        _pair_coords = [
            (
                [self.xGrid[pair[0] - 1], self.yGrid[pair[0] - 1]],
                [self.xGrid[pair[1] - 1], self.yGrid[pair[1] - 1]],
            )
            for pair in tested_pairs
        ]

        if transform:
            transform = lambda x: [
                tb.transform_coord_system(x[0]),
                tb.transform_coord_system(x[1]),
            ]

            pair_coords = [transform(coord) for coord in _pair_coords]
        else:
            pair_coords = _pair_coords

        if return_rt:
            # deprecated
            assert len(self.testedPairs) == len(self.reactionTime)
            out = (pair_coords, self.reactionTime)

        return pair_coords

    def get_fit_data(self):
        """
        Extracts the data that is necessary to fit Vseg
        """
        resp = self.Response
        tresp = tch.tensor(np.array(resp, float))

        indtestedPairs = self.indtestedPairs
        tindtestedPairs = tch.tensor(np.array(indtestedPairs, float))
        tindtestedPairs = tindtestedPairs.reshape(resp.shape[0])
        tindtestedPairs = tindtestedPairs.long()

        xGrid = self.xGrid
        yGrid = self.yGrid

        nGrid = int((xGrid.shape[0]) ** (0.5))
        n_seg = self.kSeg
        self.tresp = tresp
        self.tindtestedPairs = tindtestedPairs
        self.n_grid = nGrid
        self.n_seg = n_seg

    def _fit(
        self,
        lap_reg=5,
        lr=1e-1,
        sav_iter=True,
        max_iter=10000,
        tol=1e-6,
    ):
        self.get_fit_data()
        tch.manual_seed(10)
        seg_map = VSM(self.kSeg, self.n_grid, device="cpu")
        inferred_proba_maps = seg_map.fit(
            self.tresp,
            self.tindtestedPairs - 1,
            lap_reg=lap_reg,
            lr=lr,
            max_iter=max_iter,
            tol=tol,
            save_iter=sav_iter,
        )
        seg_proba_maps = (
            inferred_proba_maps.reshape(self.n_seg, self.n_grid, self.n_grid)
            .cpu()
            .detach()
            .numpy()
        )
        loss = np.zeros(len(seg_map.loss_iter))
        for i in range(len(seg_map.loss_iter)):
            loss[i] = seg_map.loss_iter[i].detach().numpy()

        return seg_map, inferred_proba_maps, seg_proba_maps, loss

    def fit(self, preloaded=True):
        if not preloaded:
            self.seg_map, self.inferred_proba_maps, self.seg_proba_maps, self.loss = (
                self._fit()
            )

        else:
            home = "data/fits/"
            filename = "fits_sub_{}_exp{}_session{}_cat{}_img{}.mat".format(
                self.fileinfo["subject"],
                self.fileinfo["experiment"],
                self.fileinfo["session"],
                self.fileinfo["cat"],
                self.fileinfo["img"],
            )

            self.fit_file = home + filename

            self.fit_pmap = np.moveaxis(loadmat(self.fit_file)["seg_map"], -1, 1)

            self.fit_segmap = self.fit_pmap.argmax(0)
            self.large_fit_segmap = tb.scale_im_up(self.fit_segmap, self.image.shape[0])

            self.human_seg_flag = np.asarray(
                [self._get_fit_seg_flag(pair) for pair in self.testedPairs]
            )

            self.human_psame = np.asarray(
                [self._get_fit_psame(pair) for pair in self.testedPairs]
            )

            self.is_fit = True

    def _get_fit_seg_flag(self, grid_idxs):
        unravel_idx = lambda x: np.asarray(
            np.unravel_index(x - 1, self.fit_segmap.shape[:2])
        ).T

        idx_a = unravel_idx(grid_idxs[0])
        idx_b = unravel_idx(grid_idxs[1])
        seg_flag_a = self.fit_segmap[idx_a[0], idx_a[1]]
        seg_flag_b = self.fit_segmap[idx_b[0], idx_b[1]]

        return seg_flag_a == seg_flag_b

    def _get_fit_psame(self, grid_idxs):
        unravel_idx = lambda x: np.asarray(
            np.unravel_index(x - 1, self.fit_segmap.shape[:2])
        ).T

        vec_a = self.fit_pmap[
            :, unravel_idx(grid_idxs[0])[0], unravel_idx(grid_idxs[0])[1]
        ]
        vec_b = self.fit_pmap[
            :, unravel_idx(grid_idxs[1])[0], unravel_idx(grid_idxs[1])[1]
        ]

        psame = np.dot(vec_a, vec_b)

        return psame

    def sample_pmap(self, resize=True):
        assert hasattr(self, "fit_pmap")
        _sample_pmap = lambda x: np.random.choice(list(range(len(x))), size=1, p=x)

        stop = -1
        while stop < 0:
            present = 0
            sample = np.apply_along_axis(_sample_pmap, 0, self.fit_pmap).squeeze()
            for value in range(self.kSeg):
                if value in sample:
                    present += 1
            if present < self.kSeg:
                stop = -1
            else:
                stop = 0

        if resize:
            sample = tb.scale_im_up(sample, self.image.shape[0])
        return sample

    def run_base_model(self):
        assert self.is_fit

        BaseModel = SM((0, self.image), mode="array")
        BaseModel.fit_model(
            model="c",
            n_components=np.array([self.kSeg]),
            layer_stop=1,
            keep=True,
            init=self.large_fit_segmap,
            init_eps=0.01,
            spatial_smoothing=1,
        )
        self.BaseModel = BaseModel

    def parameter_sweep(self, param="autothresh", n_pseudocoords=5):

        BaseModel = self.BaseModel

        self.get_np_coords()
        points = self.points
        pairs = self.get_tested_pairs(all_pairs=False)

        rts = BaseModel.get_decision_rts(
            points,
            pairs,
            self.testedPairs,
            auto_mult=0.01,
            boundary=None,
            use_pointwise_rts=None,
            use_pseudocoords=n_pseudocoords,
            use_evidence_integration=False,
            weighted_evidence_integration=True,
            return_df=False,
            return_responses=False,
        )

        return rts

    def run_dynamics_model(
        self, n_trials=1, smooth=1, noisy_init=False, autothresh=0.0028, boundary=1
    ):

        self.params = {
            "boundary": boundary,
            "ei_boundary": boundary,
            "wei_boundary": boundary,
            "autothresh": autothresh,
        }
        self.fit()

        dfs = []

        self.Models = []

        for i in range(n_trials):
            print("Fitting segmap trial {}".format(i))
            Model = SM((i + 1, self.image), mode="array")

            human_prior = self.sample_pmap()

            Model.fit_model(
                model="c",
                n_components=np.array([self.kSeg]),
                layer_stop=1,
                keep=True,
                init=human_prior,
                init_eps=0.05,
                spatial_smoothing=smooth,
            )

            self.get_np_coords()
            points = self.points
            pairs = self.get_tested_pairs(all_pairs=False)

            print("Running dynamics model trial {}".format(i))
            df = Model.get_decision_rts(
                points,
                pairs,
                self.testedPairs,
                auto_mult=autothresh,
                boundary={"const": [boundary, -boundary]},
                use_pointwise_rts=None,
                use_pseudocoords=10,
                use_evidence_integration=False,
                weighted_evidence_integration=True,
            )

            self.Models.append(Model)

            df["trial"] = i

            dfs.append(df)

        out = pd.concat(dfs, ignore_index=True, axis=0)
        out["human_response"] = self.Response[out.pair_idx.values]
        out["human_psame"] = self.human_psame[out.pair_idx.values]
        out["human_seg_flag"] = self.human_seg_flag[out.pair_idx.values]
        out["human_rt"] = self.reactionTime[out.pair_idx.values]
        out["k"] = self.kSeg
        out["subject"] = self.fileinfo["subject"]
        out["cat"] = self.fileinfo["cat"]
        out["img"] = self.fileinfo["img"]

        self.df = out

        # def compare_dist(df, df_new=None, key="auto_rt"):
        # human_rt_avg = df.pivot_table(
        # index=["pair_idx"], values=["human_rt"]
        # ).values

        # if df_new is not None:
        # df = df_new
        # else:
        # df = df

        # model_rt_avg = df.pivot_table(index=["pair_idx"], values=[key]).values
        # human_data = np.log(human_rt_avg[model_rt_avg != 0])
        # model_data = np.log(model_rt_avg[model_rt_avg != 0])
        # model_resc = (model_data - np.min(model_data)) / np.ptp(model_data)
        # human_resc = (human_data - np.min(human_data)) / np.ptp(human_data)

        # return jensenshannon(human_resc, model_resc)

        # self.jsd_fit = compare_dist(self.df)

        return out

    # TODO: use self._set_param to write a parameter sweep function
    def _set_param(
        self,
        value=1,
        param="bounds",
        proxy="online_rt",
        return_jsd=False,
        verbose=False,
    ):

        if proxy == "online_rt":
            self.params.update("boundary", value)
        elif proxy == "ei_rt":
            self.params.update("ei_boundary", value)
        elif proxy == "wei_rt":
            self.params.update("wei_boundary", value)

        def compare_dist(df, df_new=None, key="auto_rt"):
            human_rt_avg = df.pivot_table(
                index=["pair_idx"], values=["human_rt"]
            ).values

            if df_new is not None:
                df = df_new
            else:
                df = df

            model_rt_avg = df.pivot_table(index=["pair_idx"], values=[key]).values
            human_data = np.log(human_rt_avg[model_rt_avg != 0])
            model_data = np.log(model_rt_avg[model_rt_avg != 0])
            model_resc = (model_data - np.min(model_data)) / np.ptp(model_data)
            human_resc = (human_data - np.min(human_data)) / np.ptp(human_data)

            return jensenshannon(human_resc, model_resc)

        new_dfs = []
        if param == "bounds":
            for Model in self.Models:
                if verbose:
                    print("Refitting trial {}".format(Model.iid_idx))
                df_new = Model.reapply_bounds({"const": [value, -value]}, col=proxy)
                new_dfs.append(df_new)
        elif param == "autothresh":
            assert proxy == "auto_rt"
            for Model in self.Models:
                if verbose:
                    print("Refitting trial {}".format(Model.iid_idx))
                df_new = Model.reapply_automult(value)
                new_dfs.append(df_new)

        out = pd.concat(new_dfs, ignore_index=True, axis=0)

        if return_jsd:
            self.param_comp = compare_dist(self.df, out, key=proxy)

        self.df[proxy] = out[proxy]

        return out
