import sys

sys.path.append("../sun/src/")
import import_utils
import toolbox as tb
import numpy as np
import pandas as pd
import utils
import matplotlib.pyplot as plt
from glob import glob as glob
from natsort import natsorted as ns
from Response import Response as Res
from SegmentationMap import SegmentationMap as SM
import analysis


def _df_from_file(
    R,
    decision_bounds=(-0.69, 0.69),
    use_rt=True,
    voronoi_prior=None,
    random_prior=None,
    spatial_smoothing=True,
    trial_idx=0,
):
    """
    Generates a DataFrame from a Response class

    Parameters:
    -----------
    R : Response object
        created from a experiment response file
    decision_bounds : tup or tup-like
        used to calculated model reaction time
    use_rt : bool
        if True, get human reaction times from Response class
    voronoi_prior : np.ndarray
        must be the same shape as Response.image, used in em initial guess
    random_prior : np.ndarray
        must be the same shape as Response.image, used in em initial guess
    spatial_smoothing : bool
        if True, use spatial smoothing in EM
    trial_idx : int
        Because the Voronoi prior and random prior are generated using RNG,
        multiple trials with multiple initializations can be generated.
        However, Kmeans initialization doesn't depend on RNG.
        Therefore KMeans initialization only runs if trial_idx==0

    Returns:
    --------
    df : pd.DataFrame
        df is of type generated by analysis.get_df()
    """
    if voronoi_prior is None:
        voronoi_prior = utils.generate_random_voronoi_prior(
            *R.image.shape[:2], R.kSeg, end_iter=0.05
        )
    if random_prior is None:
        random_prior = utils.generate_random_prior(*R.image.shape[:2], R.kSeg)

    Voronoi = SM((0, R.image), mode="array")
    Random = SM((1, R.image), mode="array")
    KMeans = SM((2, R.image), mode="array")
    model = "c"
    k = R.kSeg

    if spatial_smoothing:
        print("\tSpatial smoothing ON")
        print("\t\tSegmenting Voronoi... ")
        Voronoi.fit_model(
            model=model,
            n_components=np.array([k]),
            layer_stop=1,
            keep=True,
            init=voronoi_prior,
            init_eps=0.05,
        )
        print("\t\tSegmenting Random... ")
        Random.fit_model(
            model=model,
            n_components=np.array([k]),
            layer_stop=1,
            keep=True,
            init=random_prior,
            init_eps=0.1,
        )
        if trial_idx == 0:
            print("\t\tSegmenting KMeans... ")
            KMeans.fit_model(
                model=model,
                n_components=np.array([k]),
                layer_stop=1,
                keep=True,
                init=None,
            )
    else:
        print("\tSpatial smoothing OFF")
        prior_weights = None
        print("\t\tSegmenting Voronoi... ")
        Voronoi.fit_model(
            model=model,
            n_components=np.array([k]),
            layer_stop=1,
            keep=True,
            init=voronoi_prior,
            init_eps=0.05,
            prior_weights=prior_weights,
        )
        print("\t\tSegmenting Random... ")
        Random.fit_model(
            model=model,
            n_components=np.array([k]),
            layer_stop=1,
            keep=True,
            init=random_prior,
            init_eps=0.1,
            prior_weights=prior_weights,
        )
        if trial_idx == 0:
            print("\t\tSegmenting KMeans... ")
            KMeans.fit_model(
                model=model,
                n_components=np.array([k]),
                layer_stop=1,
                keep=True,
                init=None,
                prior_weights=prior_weights,
            )
    # extract probability maps
    if trial_idx == 0:
        pmaps = {
            "Voronoi": utils.get_SegMap_pmaps(Voronoi, R.kSeg),
            "Random": utils.get_SegMap_pmaps(Random, R.kSeg),
            "KMeans": utils.get_SegMap_pmaps(KMeans, R.kSeg),
        }
    else:
        pmaps = {
            "Voronoi": utils.get_SegMap_pmaps(Voronoi, R.kSeg),
            "Random": utils.get_SegMap_pmaps(Random, R.kSeg),
        }

    if use_rt:
        pairs = R.get_tested_pairs(all_pairs=False)
        rts = R.reactionTime
        responses = R.Response
    else:
        pairs = R.get_tested_pairs()
        rts = None
        responses = None

    if trial_idx == 0:
        df = pd.concat(
            [
                analysis.get_df(
                    pairs,
                    pmaps["Voronoi"],
                    decision_bounds=(decision_bounds[0], decision_bounds[1]),
                    reaction_times=rts,
                    responses=responses,
                    condition="voronoi",
                ),
                analysis.get_df(
                    pairs,
                    pmaps["Random"],
                    decision_bounds=(decision_bounds[0], decision_bounds[1]),
                    reaction_times=rts,
                    responses=responses,
                    condition="random",
                ),
                analysis.get_df(
                    pairs,
                    pmaps["KMeans"],
                    decision_bounds=(decision_bounds[0], decision_bounds[1]),
                    reaction_times=rts,
                    responses=responses,
                    condition="kmeans",
                ),
            ],
            axis=0,
            ignore_index=True,
        )
    else:
        df = pd.concat(
            [
                analysis.get_df(
                    pairs,
                    pmaps["Voronoi"],
                    decision_bounds=(decision_bounds[0], decision_bounds[1]),
                    reaction_times=rts,
                    responses=responses,
                    condition="voronoi",
                ),
                analysis.get_df(
                    pairs,
                    pmaps["Random"],
                    decision_bounds=(decision_bounds[0], decision_bounds[1]),
                    reaction_times=rts,
                    responses=responses,
                    condition="random",
                ),
            ]
        )

    df["k"] = k
    for item in list(R.fileinfo.keys())[1:-1]:
        df[item] = R.fileinfo[item]

    return df


def df_from_file(file, decision_bounds=(-0.69, 0.69), use_rt=True, trial_idx=0):
    """
    Wrapper around _df_from_file that runs fits for Voronoi initialization,
    random initialization, and KMeans initialization with both spatial smoothing
    on and spatial smoothing off

    Parameters:
    -----------
    file : str
        filepath to experiment file
    decision_bounds : tup or tup-like
        used to calculated model reaction time
    use_rt : bool
        if True, get human reaction times from Response class
    trial_idx : int
        Because the Voronoi prior and random prior are generated using RNG,
        multiple trials with multiple initializations can be generated. However,
        Kmeans initialization doesn't depend on RNG. Therefore KMeans
        initialization only runs if trial_idx==0

    Returns:
    --------
    df : pd.DataFrame
        df is of type generated by analysis.get_df()
    """
    print("Importing file: {}".format(file))
    R = Res(file)
    # create random initial Voronoi/Random priors
    print("\tGenerating voronoi prior...")
    vd = utils.generate_random_voronoi_prior(*R.image.shape[:2], R.kSeg, end_iter=0.05)
    print("\tGenerating random prior...")
    rand = utils.generate_random_prior(*R.image.shape[:2], R.kSeg)
    df_smooth = _df_from_file(
        R,
        decision_bounds=decision_bounds,
        use_rt=use_rt,
        trial_idx=trial_idx,
        spatial_smoothing=True,
        voronoi_prior=vd,
        random_prior=rand,
    )
    df_smooth["smoothness"] = 1
    df_unsmooth = _df_from_file(
        R,
        decision_bounds=decision_bounds,
        use_rt=use_rt,
        trial_idx=trial_idx,
        spatial_smoothing=False,
        voronoi_prior=vd,
        random_prior=rand,
    )
    df_unsmooth["smoothness"] = 0

    df_out = pd.concat([df_smooth, df_unsmooth], axis=0, ignore_index=True)

    return df_out


def run_trials(file, n_trials):
    """
    Wrapper around df_from_file that runs that function multiple times

    Parameters:
    -----------
    file : str
        filepath to experiment file
    n_trials : int
        The total number of trials to run, or, the total number of Voronoi and
        random priors generated using RNG per image
    Returns:
    --------
    df : pd.DataFrame
        df is of type generated by analysis.get_df()
    """
    dfs = []
    for i in range(n_trials):
        print("File: {} | Trial {}".format(file, i))
        print("\t")
        df = df_from_file(file, trial_idx=i)
        df["trial"] = i
        dfs.append(df)
        print("\t")
    out = pd.concat(dfs, axis=0, ignore_index=True)

    return out


def run_all_files(files, n_trials=10):
    """
    Wrapper around run_trials that runs that function for every file

    Parameters:
    -----------
    files : list of str
        list of filenames as str for input into run_trials
    n_trials : int
        The total number of trials per file
    Returns:
    --------
    df : pd.DataFrame
        df is of type generated by analysis.get_df()
    """
    out = pd.concat(
        [run_trials(file, n_trials) for file in files], axis=0, ignore_index=True
    )

    return out


if __name__ == "__main__":
    print("Hello")

    files = ns(glob("data/*"))

    df = run_all_files(files)

    df.to_csv("reaction_time_responses_model_all_files.csv")
